const stems=[
{hanja:'甲',ko:'갑',yinYang:'양',element:'목',image:'큰 나무'},{hanja:'乙',ko:'을',yinYang:'음',element:'목',image:'덩굴과 풀'},{hanja:'丙',ko:'병',yinYang:'양',element:'화',image:'태양'},{hanja:'丁',ko:'정',yinYang:'음',element:'화',image:'촛불'},{hanja:'戊',ko:'무',yinYang:'양',element:'토',image:'산'},{hanja:'己',ko:'기',yinYang:'음',element:'토',image:'밭'},{hanja:'庚',ko:'경',yinYang:'양',element:'금',image:'쇠'},{hanja:'辛',ko:'신',yinYang:'음',element:'금',image:'보석'},{hanja:'壬',ko:'임',yinYang:'양',element:'수',image:'바다'},{hanja:'癸',ko:'계',yinYang:'음',element:'수',image:'비'}];
const branches=[
{hanja:'子',ko:'자',animal:'쥐',element:'수'},{hanja:'丑',ko:'축',animal:'소',element:'토'},{hanja:'寅',ko:'인',animal:'호랑이',element:'목'},{hanja:'卯',ko:'묘',animal:'토끼',element:'목'},{hanja:'辰',ko:'진',animal:'용',element:'토'},{hanja:'巳',ko:'사',animal:'뱀',element:'화'},{hanja:'午',ko:'오',animal:'말',element:'화'},{hanja:'未',ko:'미',animal:'양',element:'토'},{hanja:'申',ko:'신',animal:'원숭이',element:'금'},{hanja:'酉',ko:'유',animal:'닭',element:'금'},{hanja:'戌',ko:'술',animal:'개',element:'토'},{hanja:'亥',ko:'해',animal:'돼지',element:'수'}];
const elements={목:{label:'목',color:'#2f8f7b'},화:{label:'화',color:'#d9614c'},토:{label:'토',color:'#c4912c'},금:{label:'금',color:'#7c8791'},수:{label:'수',color:'#3d78a7'}};
const monthTerms=[{month:1,day:6,branch:1},{month:2,day:4,branch:2},{month:3,day:6,branch:3},{month:4,day:5,branch:4},{month:5,day:6,branch:5},{month:6,day:6,branch:6},{month:7,day:7,branch:7},{month:8,day:8,branch:8},{month:9,day:8,branch:9},{month:10,day:8,branch:10},{month:11,day:7,branch:11},{month:12,day:7,branch:0}];
const lunarInfo=[0x04bd8,0x04ae0,0x0a570,0x054d5,0x0d260,0x0d950,0x16554,0x056a0,0x09ad0,0x055d2,0x04ae0,0x0a5b6,0x0a4d0,0x0d250,0x1d255,0x0b540,0x0d6a0,0x0ada2,0x095b0,0x14977,0x04970,0x0a4b0,0x0b4b5,0x06a50,0x06d40,0x1ab54,0x02b60,0x09570,0x052f2,0x04970,0x06566,0x0d4a0,0x0ea50,0x06e95,0x05ad0,0x02b60,0x186e3,0x092e0,0x1c8d7,0x0c950,0x0d4a0,0x1d8a6,0x0b550,0x056a0,0x1a5b4,0x025d0,0x092d0,0x0d2b2,0x0a950,0x0b557,0x06ca0,0x0b550,0x15355,0x04da0,0x0a5d0,0x14573,0x052d0,0x0a9a8,0x0e950,0x06aa0,0x0aea6,0x0ab50,0x04b60,0x0aae4,0x0a570,0x05260,0x0f263,0x0d950,0x05b57,0x056a0,0x096d0,0x04dd5,0x04ad0,0x0a4d0,0x0d4d4,0x0d250,0x0d558,0x0b540,0x0b6a0,0x195a6,0x095b0,0x049b0,0x0a974,0x0a4b0,0x0b27a,0x06a50,0x06d40,0x0af46,0x0ab60,0x09570,0x04af5,0x04970,0x064b0,0x074a3,0x0ea50,0x06b58,0x05ac0,0x0ab60,0x096d5,0x092e0,0x0c960,0x0d954,0x0d4a0,0x0da50,0x07552,0x056a0,0x0abb7,0x025d0,0x092d0,0x0cab5,0x0a950,0x0b4a0,0x0baa4,0x0ad50,0x055d9,0x04ba0,0x0a5b0,0x15176,0x052b0,0x0a930,0x07954,0x06aa0,0x0ad50,0x05b52,0x04b60,0x0a6e6,0x0a4e0,0x0d260,0x0ea65,0x0d530,0x05aa0,0x076a3,0x096d0,0x04bd7,0x04ad0,0x0a4d0,0x1d0b6,0x0d250,0x0d520,0x0dd45,0x0b5a0,0x056d0,0x055b2,0x049b0,0x0a577,0x0a4b0,0x0aa50,0x1b255,0x06d20,0x0ada0,0x14b63];
const monthStemStarts=[2,4,6,8,0],hourStemStarts=[0,2,4,6,8];
const $=s=>document.querySelector(s);const form=$('#birthForm'),tabs=document.querySelectorAll('.tab');let currentChart=null,activeTab='overall';
const mod=(v,l)=>((v%l)+l)%l;function sexagenary(i){const stem=stems[mod(i,10)],branch=branches[mod(i,12)];return{index:mod(i,60),stem,branch,hanja:stem.hanja+branch.hanja,ko:stem.ko+branch.ko};}
function getJulianDay(y,m,d){const a=Math.floor((14-m)/12),yy=y+4800-a,mm=m+12*a-3;return d+Math.floor((153*mm+2)/5)+365*yy+Math.floor(yy/4)-Math.floor(yy/100)+Math.floor(yy/400)-32045;}
function shifted(y,m,d,o){const date=new Date(y,m-1,d+o);return{year:date.getFullYear(),month:date.getMonth()+1,day:date.getDate()};}
const ly=y=>lunarInfo[y-1900],leapMonth=y=>ly(y)&0xf,leapDays=y=>leapMonth(y)?(ly(y)&0x10000?30:29):0,lunarMonthDays=(y,m)=>ly(y)&(0x10000>>m)?30:29;
function lunarYearDays(y){let sum=348;for(let mask=0x8000;mask>0x8;mask>>=1)if(ly(y)&mask)sum++;return sum+leapDays(y);}
function lunarToSolar(y,m,d,isLeap=false){if(y<1900||y>2050)throw new Error('음력 변환은 1900년부터 2050년까지만 지원합니다.');if(m<1||m>12)throw new Error('음력 월을 확인해 주세요.');const leap=leapMonth(y),max=isLeap?leapDays(y):lunarMonthDays(y,m);if(isLeap&&leap!==m)throw new Error(`${y}년에는 음력 ${m}월 윤달이 없습니다.`);if(d<1||d>max)throw new Error(`음력 ${m}월은 ${max}일까지 있습니다.`);let offset=0;for(let yy=1900;yy<y;yy++)offset+=lunarYearDays(yy);for(let mm=1;mm<m;mm++){offset+=lunarMonthDays(y,mm);if(leap===mm)offset+=leapDays(y);}if(isLeap)offset+=lunarMonthDays(y,m);offset+=d-1;const solar=new Date(1900,0,31);solar.setDate(solar.getDate()+offset);return{year:solar.getFullYear(),month:solar.getMonth()+1,day:solar.getDate()};}
function resolveInputDate(dateValue,calendarType,isLeap){const [inputYear,inputMonth,inputDay]=dateValue.split('-').map(Number);return calendarType==='lunar'?{inputYear,inputMonth,inputDay,calendarType,isLeapMonth:isLeap,...lunarToSolar(inputYear,inputMonth,inputDay,isLeap)}:{inputYear,inputMonth,inputDay,calendarType,isLeapMonth:false,year:inputYear,month:inputMonth,day:inputDay};}
function getTermDate(y,t){return new Date(y,t.month-1,t.day)}function adjacentTerms(y,m,d,h,min){const birth=new Date(y,m-1,d,h,min),dates=[];for(let yy=y-1;yy<=y+1;yy++)for(const t of monthTerms)dates.push(getTermDate(yy,t));dates.sort((a,b)=>a-b);return{birth,prev:[...dates].reverse().find(x=>x<birth)||dates[0],next:dates.find(x=>x>birth)||dates.at(-1)}}
function getYearPillar(y,m,d){const sy=m<2||(m===2&&d<4)?y-1:y;return sexagenary(sy-4)}
function findCycleIndex(si,bi){for(let i=0;i<60;i++)if(i%10===si&&i%12===bi)return i;return 0}
function getMonthPillar(yearPillar,m,d){let term=monthTerms[0];for(const c of monthTerms)if(m>c.month||(m===c.month&&d>=c.day))term=c;if(m===1&&d<6)term=monthTerms[11];const ysi=stems.indexOf(yearPillar.stem),start=monthStemStarts[ysi%5],off=mod(term.branch-2,12),si=mod(start+off,10);return{...sexagenary(findCycleIndex(si,term.branch)),termBranch:term.branch}}
function getDayPillar(y,m,d){return sexagenary(getJulianDay(y,m,d)+49)}function getHourPillar(dayPillar,h){const bi=h===23?0:Math.floor((h+1)/2)%12,di=stems.indexOf(dayPillar.stem),si=mod(hourStemStarts[di%5]+bi,10);return sexagenary(findCycleIndex(si,bi));}
function countElements(pillars){const counts={목:0,화:0,토:0,금:0,수:0};for(const p of pillars){counts[p.stem.element]++;counts[p.branch.element]++;}return counts;}
function buildChart(dateValue,timeValue,yajaEnabled=true,gender='neutral',calendarType='solar',isLeap=false){const r=resolveInputDate(dateValue,calendarType,isLeap),{year,month,day}=r,[hour,minute]=timeValue.split(':').map(Number),isYaja=hour===23&&minute>=30,next=shifted(year,month,day,1),dayDate=!yajaEnabled&&isYaja?next:{year,month,day},hourStemDate=yajaEnabled&&isYaja?next:dayDate,yp=getYearPillar(year,month,day),mp=getMonthPillar(yp,month,day),dp=getDayPillar(dayDate.year,dayDate.month,dayDate.day),hp=getHourPillar(getDayPillar(hourStemDate.year,hourStemDate.month,hourStemDate.day),hour),pillars=[{key:'year',label:'년주',hint:'가문과 초년',...yp},{key:'month',label:'월주',hint:'사회와 일',...mp},{key:'day',label:'일주',hint:'나 자신',...dp},{key:'hour',label:'시주',hint:'재능과 미래',...hp}];return{year,month,day,hour,minute,inputYear:r.inputYear,inputMonth:r.inputMonth,inputDay:r.inputDay,calendarType:r.calendarType,isLeapMonth:r.isLeapMonth,yajaEnabled,yajaApplied:yajaEnabled&&isYaja,pillars,dayMaster:dp.stem,counts:countElements(pillars),gender};}
function dominantWeak(counts){const ranked=Object.entries(counts).sort((a,b)=>b[1]-a[1]);return{dominant:ranked[0][0],weak:ranked.at(-1)[0],ranked};}
function batchim(t){const c=t.charCodeAt(t.length-1);return c>=0xac00&&c<=0xd7a3&&(c-0xac00)%28!==0}const subj=t=>batchim(t)?'이':'가',obj=t=>batchim(t)?'을':'를',displayName=()=>$('#name').value.trim()?`${$('#name').value.trim()}님`:'당신';
function daeunDirection(yp,gender){const yang=yp.stem.yinYang==='양';if(gender==='male')return yang?1:-1;if(gender==='female')return yang?-1:1;return yang?1:-1}function daeunStartAge(c,dir){const{birth,prev,next}=adjacentTerms(c.year,c.month,c.day,c.hour,c.minute),target=dir===1?next:prev;return Math.max(1,Math.round(Math.abs(target-birth)/86400000/3));}
function buildDaeun(c){const dir=daeunDirection(c.pillars[0],c.gender),startAge=daeunStartAge(c,dir),mi=c.pillars[1].index;return{direction:dir,directionLabel:(dir===1?'순행':'역행')+(c.gender==='neutral'?' 임시':''),startAge,cycles:Array.from({length:8},(_,i)=>{const p=sexagenary(mi+dir*(i+1)),ageStart=startAge+i*10;return{...p,ageStart,ageEnd:ageStart+9,calendarStart:c.year+ageStart,calendarEnd:c.year+ageStart+9}})}}
function currentAge(c){const today=new Date();let age=today.getFullYear()-c.year;if(today.getMonth()+1<c.month||(today.getMonth()+1===c.month&&today.getDate()<c.day))age--;return age;}
function renderDaeun(c){const d=buildDaeun(c),age=currentAge(c);$('#daeunSummary').textContent=`${d.directionLabel} · ${d.startAge}세 시작`;$('#daeunNote').textContent=`${c.gender==='neutral'?'성별 미선택: 연간 음양 기준 임시 표시':'성별과 연간 음양 기준'}. 절기일은 근사값이며 전문 만세력과 차이가 날 수 있습니다.`;$('#daeunList').innerHTML=d.cycles.map(x=>`<article class="daeun-card${age>=x.ageStart&&age<=x.ageEnd?' active':''}"><div><span>${x.ageStart}-${x.ageEnd}세</span><strong>${x.hanja}</strong><em>${x.ko} · ${x.stem.element}/${x.branch.element}</em></div><p>${x.calendarStart}-${x.calendarEnd}</p><small>${x.stem.element===c.dayMaster.element||x.branch.element===c.dayMaster.element?'자기 색이 강해지는 시기라 주도권을 잡기 쉽습니다.':'현실적인 선택과 환경 변화가 중요해지는 시기입니다.'}</small></article>`).join('');}
function renderBars(counts){const max=Math.max(...Object.values(counts),1);$('#elementBars').innerHTML=Object.entries(elements).map(([k,info])=>{const v=counts[k],w=v===0?0:Math.max(8,Math.round(v/max*100));return`<div class="element-row"><strong>${info.label}</strong><div class="bar-track" aria-hidden="true"><div class="bar-fill" style="width:${w}%;background:${info.color};"></div></div><span>${v}</span></div>`}).join('');}
function renderChart(c){const name=displayName(),{dominant,weak}=dominantWeak(c.counts),yaja=c.yajaApplied?' · 야자시 적용':c.yajaEnabled?' · 야자시 대기':'',cal=c.calendarType==='lunar'?`음력${c.isLeapMonth?' 윤달':''} ${c.inputYear}.${String(c.inputMonth).padStart(2,'0')}.${String(c.inputDay).padStart(2,'0')} → `:'양력 ';$('#resultKicker').textContent=`${cal}${c.year}.${String(c.month).padStart(2,'0')}.${String(c.day).padStart(2,'0')} ${String(c.hour).padStart(2,'0')}:${String(c.minute).padStart(2,'0')}${yaja}`;$('#resultTitle').textContent=`${name}의 중심 기운은 ${c.dayMaster.hanja}(${c.dayMaster.ko}) ${c.dayMaster.element}입니다`;$('#dayMasterBadge').textContent=`${c.dayMaster.ko.toUpperCase()} ${c.dayMaster.element}`;const ps=[...c.pillars].reverse();$('#pillarGrid').innerHTML=ps.map(p=>`<div class="pillar-title">${p.label}</div>`).join('')+ps.map(p=>`<article class="palja-cell" data-element="${p.stem.element}"><span>천간 · ${p.stem.ko}</span><strong>${p.stem.hanja}</strong><small>${p.stem.element} · ${p.stem.yinYang}</small></article>`).join('')+ps.map(p=>`<article class="palja-cell" data-element="${p.branch.element}"><span>지지 · ${p.branch.ko}</span><strong>${p.branch.hanja}</strong><small>${p.branch.element} · ${p.branch.animal}</small></article>`).join('');$('#balanceSummary').textContent=`${dominant} 강함 · ${weak} 보완`;renderBars(c.counts);renderDaeun(c);setActiveTab($('#focus').value==='mind'?'overall':$('#focus').value);}
const advice=e=>({목:'목은 방향을 세우고 키우는 힘입니다. 계획을 작게 쪼개 매일 자라나는 방식으로 움직일 때 운이 붙습니다.',화:'화는 드러내고 연결하는 힘입니다. 말, 발표, 홍보처럼 밖으로 보이는 활동에서 기회가 열립니다.',토:'토는 받아들이고 안정시키는 힘입니다. 관리와 조율에서 신뢰를 얻습니다.',금:'금은 자르고 정리하는 힘입니다. 기준을 세우면 성과와 돈의 흐름이 또렷해집니다.',수:'수는 흐르고 축적하는 힘입니다. 공부, 정보, 이동, 연구에서 장기 운이 만들어집니다.'}[e]);
const support=e=>({목:'초록 계열, 산책, 기록 습관',화:'붉은 계열, 발표, 오전 루틴',토:'노란 계열, 정리, 꾸준한 식사 리듬',금:'흰색 계열, 숫자 관리, 마감 설정',수:'검정과 파랑, 수면 회복, 조용한 공부'}[e]);
function yearlyPillar(y){return sexagenary(y-4)}
function getReading(c,tab){const name=displayName(),{dominant,weak}=dominantWeak(c.counts),dm=c.dayMaster.element,yp=c.pillars[0],mp=c.pillars[1],dp=c.pillars[2],hp=c.pillars[3],yf=yearlyPillar(new Date().getFullYear()),weakObj=`${weak}${obj(weak)}`,domSub=`${dominant}${subj(dominant)}`;const common=`${dominant} 기운이 가장 두드러지고 ${weak} 기운은 의식적으로 보완하면 좋습니다. 보완 키워드는 ${support(weak)}입니다.`;return({overall:`<p>${name}은 ${c.dayMaster.image} 같은 ${c.dayMaster.ko} 일간입니다. ${advice(dm)}</p><p>${common} 강한 기운은 재능이지만 과하면 고집이 되니 약한 기운을 생활 습관으로 채우는 쪽이 빠릅니다.</p><p>년주 ${yp.hanja}는 첫인상과 초년의 바탕, 월주 ${mp.hanja}는 사회에서 쓰는 힘을 보여줍니다.</p><p>일주 ${dp.hanja}는 가까운 사람 앞에서의 본모습이고, 시주 ${hp.hanja}는 재능의 방향과 후반 운을 봅니다.</p><p>지금 당장 성과가 작아 보여도 약한 ${weak} 기운을 루틴으로 보완하면 흐름이 안정됩니다.</p>`,career:`<p>일운은 월주 ${mp.hanja}의 영향을 크게 받습니다. ${mp.stem.element} 기운이 일의 방식에 깔려 있어 성과는 속도보다 구조를 만들 때 안정됩니다.</p><p>${domSub} 강한 날에는 밀어붙이고, ${weakObj} 보완하는 날에는 정리와 협업을 잡는 흐름이 좋습니다.</p><p>직업적으로는 일간의 ${dm} 기운을 억지로 바꾸기보다 잘 쓰는 편이 좋습니다. ${advice(dm)}</p><p>돈의 흐름은 강한 오행을 바로 쓰는 방식보다 약한 오행을 보완할 때 안정됩니다.</p><p>올해 ${yf.hanja}의 ${yf.stem.element}/${yf.branch.element} 기운은 기존 방식에 변화를 줍니다.</p>`,love:`<p>부족한 ${weak} 기운을 가진 사람이나 환경이 귀인이 되기 쉽습니다. 낯선 조언을 바로 밀어내지 않을 때 관계운이 살아납니다.</p><p>일주 ${dp.hanja}는 가까운 관계에서 드러나는 모습입니다. 마음이 급할수록 한 번 쉬고 말하면 매력이 더 선명하게 전달됩니다.</p><p>${dominant} 기운이 강하면 내 방식이 선명해지는 대신 상대가 숨 쉴 공간이 줄어들 수 있습니다.</p><p>좋은 인연은 부족한 ${weak} 기운을 무리 없이 채워주는 사람에게서 오기 쉽습니다.</p><p>감정, 이유, 원하는 행동을 따로 말하면 오해가 줄고 관계 회복 속도도 빨라집니다.</p>`,timing:`<p>${new Date().getFullYear()}년의 흐름은 ${yf.hanja}(${yf.ko})입니다. 올해 들어오는 ${yf.stem.element}/${yf.branch.element} 기운은 ${dm} 일간에게 새로운 균형점을 요구합니다.</p><p>중요한 결정은 ${dominant} 기운이 과열될 때보다 ${weak}을 채운 뒤가 좋습니다.</p><p>좋은 시기는 기운이 강해지는 때가 아니라 균형이 맞는 때입니다.</p><p>이동, 이직, 계약, 고백처럼 방향을 바꾸는 일은 하루 기분보다 준비 상태를 기준으로 보세요.</p><p>${support(weak)}을 작은 루틴으로 만들면 시기의 도움을 더 잘 받습니다.</p>`})[tab];}
function setActiveTab(tabName){activeTab=tabName;tabs.forEach(t=>t.classList.toggle('active',t.dataset.tab===tabName));if(currentChart)$('#readingText').innerHTML=getReading(currentChart,tabName)}
function setDefaultDate(){const input=$('#birthDate');input.min='1900-01-01';input.max='2050-12-31';if(!input.value)input.value='1995-05-15'}
function syncCalendarControls(){const lunar=$('#calendarType').value==='lunar',leap=$('#leapMonth');$('#dateLabel').textContent=lunar?'음력 생년월일':'양력 생년월일';leap.disabled=!lunar;if(!lunar)leap.checked=false;$('.lunar-switch').classList.toggle('disabled',!lunar)}
function updateChartFromInputs(){const date=$('#birthDate').value,time=$('#birthTime').value;if(!date||!time)return;try{currentChart=buildChart(date,time,$('#yajaTime').checked,$('#gender').value,$('#calendarType').value,$('#leapMonth').checked);renderChart(currentChart)}catch(e){$('#resultKicker').textContent='날짜 입력 확인';$('#resultTitle').textContent=e.message;$('#dayMasterBadge').textContent='확인'}}
form.addEventListener('submit',e=>{e.preventDefault();updateChartFromInputs()});$('#yajaTime').addEventListener('change',updateChartFromInputs);$('#gender').addEventListener('change',updateChartFromInputs);$('#calendarType').addEventListener('change',()=>{syncCalendarControls();updateChartFromInputs()});$('#leapMonth').addEventListener('change',updateChartFromInputs);tabs.forEach(t=>t.addEventListener('click',()=>setActiveTab(t.dataset.tab)));setDefaultDate();syncCalendarControls();updateChartFromInputs();
